services:
  a0-prerelease:
    container_name: A0-prerelease
    build:
      context: ./docker/run
      dockerfile: Dockerfile
      args:
        GIT_REF: v0.9.8-custom-pre  # Change this to the desired pre-release tag
        CACHE_DATE: ${CACHE_DATE:-none}
    volumes:
      - ./docker/run/fs/per:/per
    ports:
      - "8892:80"
    restart: unless-stopped

